/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.films.struts.action;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.upload.FormFile;

import com.films.domain.Area;
import com.films.domain.Film;
import com.films.domain.Sort;
import com.films.service.inter.IAreaService;
import com.films.service.inter.IFilmService;
import com.films.service.inter.ISortService;
import com.films.struts.form.MovieForm;
import com.films.utils.MyTools;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2012
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class FilmCenterAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private IFilmService filmService;
	private ISortService sortService;
	private IAreaService areaService;

	public void setFilmService(IFilmService filmService) {
		this.filmService = filmService;
	}

	public void setSortService(ISortService sortService) {
		this.sortService = sortService;
	}

	public void setAreaService(IAreaService areaService) {
		this.areaService = areaService;
	}

	public ActionForward postMovie(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		// TODO Auto-generated method stub
		request.setCharacterEncoding("utf-8");
		response.setContentType("text/html;charset=utf-8");
		PrintWriter out = response.getWriter();
		Film film = new Film();
		MovieForm movieForm = (MovieForm) form;
		FormFile photo = movieForm.getFilmPhoto();
		film.setFfilmName(movieForm.getFFilmName());
		film.setFdiretor(movieForm.getFDirector());
		film.setFplay(movieForm.getFPlay());
		film.setFlanguage(movieForm.getFLanguage());
		film.setFlong(Integer.parseInt(movieForm.getFLong()));
		film.setFdate(movieForm.getFDate());
		film.setFtype(movieForm.getFType());
		film.setFintro(movieForm.getFIntro());

		//get sort
		Sort sort = (Sort) sortService.findById(Sort.class, Integer.valueOf(movieForm.getSortID()));
		
		//get area
		Area area = (Area) areaService.findById(Area.class, Integer.valueOf(movieForm.getFAid()));

		film.setArea(area);
		film.setSort(sort);
		filmService.save(film);
		
		String fphoto = MyTools.uploadFilmPhoto(request, photo, film.getFid()+"");
		film.setFphoto(fphoto);
		filmService.save(film);
		
		out.print("<script language='javascript'>alert('post success!');window.history.back(-1);</script>");
		return null;
	}
}