/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.films.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;


/** 
 * MyEclipse Struts
 * Creation date: 10-07-2012
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class ReloginAction extends DispatchAction {
	
	public ActionForward goLogin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goLogin");
	}
	
	public ActionForward goReg(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goReg");
	}
	
	public ActionForward goUserHome(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		if(request.getSession().getAttribute("loginUser")!=null){
			return mapping.findForward("goUserHome");
		}else{	
			return mapping.findForward("index");
		}	
	}
}