/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.films.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.films.service.inter.IFilmService;
import com.films.struts.form.SearchForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-06-2012
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class SearchAction extends DispatchAction {
	
	private IFilmService filmService;
	
	public void setFilmService(IFilmService filmService) {
		this.filmService = filmService;
	}

	public ActionForward search(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		SearchForm searchForm = (SearchForm) form;
		List list = filmService.getFilmByKW(searchForm.getKeyWord());
		if(list.size()!=0){
			request.setAttribute("film", list);
			request.setAttribute("size", list.size());
			return mapping.findForward("bingo");
		}else{
			return mapping.findForward("404");
		}
	}
}