/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.films.struts.action;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.upload.FormFile;

import com.films.domain.Users;
import com.films.service.inter.IUserService;
import com.films.struts.form.UserPhotoForm;
import com.films.utils.MyTools;

/** 
 * MyEclipse Struts
 * Creation date: 10-23-2012
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class UserInfoAction extends DispatchAction {


	Users user;
	private IUserService userService;

	public void setUserService(IUserService userService) {
		this.userService = userService;
	}
	
	public ActionForward baseInfo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		// TODO Auto-generated method stub
		request.setCharacterEncoding("utf-8");
		response.setContentType("text/html;charset=utf-8");
		PrintWriter out = response.getWriter();
		String uname = request.getParameter("nickName");
		String usex = request.getParameter("sex");
		String birthDay = request.getParameter("birthDay");
		user = (Users) request.getSession().getAttribute("loginUser");
		user.setUname(uname);
		user.setUsex(usex);
		user.setUbirth(birthDay);
		userService.update(user);
		out.println("修改成功(Change Success!)");
		return null;
	}
	
	public ActionForward detailInfo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		// TODO Auto-generated method stub
		request.setCharacterEncoding("utf-8");
		response.setContentType("text/html;charset=utf-8");
		PrintWriter out = response.getWriter();
		String trueName = request.getParameter("trueName");
		String mobile = request.getParameter("mobile");
		String uqq = request.getParameter("uqq");
		String IDNumber = request.getParameter("IDNumber");
		user = (Users) request.getSession().getAttribute("loginUser");
		user.setUrealName(trueName);
		user.setUphone(mobile);
		user.setUqq(uqq);
		user.setUidcard(IDNumber);
		userService.update(user);
		out.println("修改成功(Change Success!)");
		return null;
	}
	
	public ActionForward savaPhoto(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		// TODO Auto-generated method stub
		Users user = (Users) request.getSession().getAttribute("loginUser");
		UserPhotoForm userPhotoForm = (UserPhotoForm) form;
		FormFile memberPhoto = userPhotoForm.getMemberPhoto();
		System.out.println(memberPhoto.getFileName());
		String userPhotoName = MyTools.uploadUserPhoto(request, memberPhoto, user.getUid()+"");
		user.setUphoto(userPhotoName);
		userService.update(user);		
		return mapping.findForward("goUploadUI");
	}
}