/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.films.struts.action;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.films.domain.Users;
import com.films.service.inter.IUserService;
import com.films.struts.form.AddUserForm;
import com.films.utils.MyTools;

/** 
 * MyEclipse Struts
 * Creation date: 10-21-2012
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class UserCenterAction extends DispatchAction {
	
	Users user;
	private IUserService userService;

	public void setUserService(IUserService userService) {
		this.userService = userService;
	}
	
	public ActionForward addUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("addUserUI");
	}
	
	public ActionForward submitUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		AddUserForm addUserForm = (AddUserForm) form;
		user = new Users();
		user.setUemail((addUserForm.getEmail()));
		user.setUsex(addUserForm.getSex());
		user.setUrole(addUserForm.getRole());
		user.setUpassword(MyTools.MD5(addUserForm.getPassword()));
		userService.save(user);
		return mapping.findForward("goUserCenter");
	}
	
	public ActionForward delUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		// TODO Auto-generated method stub
		request.setCharacterEncoding("utf-8");
		response.setContentType("text/html;charset=utf-8");
		PrintWriter out = response.getWriter();
		String uid = (String) request.getParameter("uid");
		user = (Users) userService.findById(Users.class, Integer.valueOf(uid));
		userService.delete(user);
		out.print("<script language='javascript'>alert('删除成功(Delete Success)！');window.history.back(-1);</script>");
		return null;
	}
	
	public ActionForward editUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		// TODO Auto-generated method stub
		String uid = (String) request.getParameter("uid");
		user = (Users) userService.findById(Users.class, Integer.valueOf(uid));
		request.setAttribute("user", user);
		return mapping.findForward("goEditUser");
	}
	
	public ActionForward editSubmit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		// TODO Auto-generated method stub
		AddUserForm addUserForm = (AddUserForm) form;
		user = (Users) userService.findById(Users.class, Integer.valueOf(addUserForm.getUid()));
		String pwd = user.getUpassword();
		user.setUemail(addUserForm.getEmail());
		user.setUsex(addUserForm.getSex());
		user.setUrole(addUserForm.getRole());
		if(!pwd.equals(addUserForm.getPassword())){
			user.setUpassword(MyTools.MD5(addUserForm.getPassword()));			
		}		
		userService.update(user);
		return mapping.findForward("goUserCenter");
	}
}