/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.films.struts.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2012
 * 
 * XDoclet definition:
 * @struts.form name="movieForm"
 */
public class MovieForm extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/*
	 * Generated Methods
	 */
	private String fid;
	private String FFilmName;
	private String FDirector;
	private String FPlay;
	private String FLanguage;
	private String FLong;
	private String FDate;
	private String FType;
	private String sortID;
	private String FAid;
	private String FIntro;
	private String FPhoto;
	private FormFile filmPhoto;
	
	
	public String getFid() {
		return fid;
	}
	public void setFid(String fid) {
		this.fid = fid;
	}
	public String getFAid() {
		return FAid;
	}
	public void setFAid(String fAid) {
		FAid = fAid;
	}
	public FormFile getFilmPhoto() {
		return filmPhoto;
	}
	public void setFilmPhoto(FormFile filmPhoto) {
		this.filmPhoto = filmPhoto;
	}
	public String getFFilmName() {
		return FFilmName;
	}
	public void setFFilmName(String fFilmName) {
		FFilmName = fFilmName;
	}
	public String getFDirector() {
		return FDirector;
	}
	public void setFDirector(String fDirector) {
		FDirector = fDirector;
	}
	public String getFPlay() {
		return FPlay;
	}
	public void setFPlay(String fPlay) {
		FPlay = fPlay;
	}
	public String getFLanguage() {
		return FLanguage;
	}
	public void setFLanguage(String fLanguage) {
		FLanguage = fLanguage;
	}
	public String getFLong() {
		return FLong;
	}
	public void setFLong(String fLong) {
		FLong = fLong;
	}
	public String getFDate() {
		return FDate;
	}
	public void setFDate(String fDate) {
		FDate = fDate;
	}
	public String getFType() {
		return FType;
	}
	public void setFType(String fType) {
		FType = fType;
	}

	public String getSortID() {
		return sortID;
	}
	public void setSortID(String sortID) {
		this.sortID = sortID;
	}
	public String getFIntro() {
		return FIntro;
	}
	public void setFIntro(String fIntro) {
		FIntro = fIntro;
	}
	public String getFPhoto() {
		return FPhoto;
	}
	public void setFPhoto(String fPhoto) {
		FPhoto = fPhoto;
	}
}