/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.films.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-18-2012
 * 
 * XDoclet definition:
 * @struts.form name="showTableForm"
 */
public class ShowTableForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String tFID;
	private String ffname;
	private String tDate;
	private String tTime;
	private String tTicketPrice;
	private String tHallID;
	private String ttid;

	public String getFfname() {
		return ffname;
	}
	public void setFfname(String ffname) {
		this.ffname = ffname;
	}
	public String getTtid() {
		return ttid;
	}
	public void setTtid(String ttid) {
		this.ttid = ttid;
	}
	public String gettFID() {
		return tFID;
	}
	public void settFID(String tFID) {
		this.tFID = tFID;
	}
	public String gettDate() {
		return tDate;
	}
	public void settDate(String tDate) {
		this.tDate = tDate;
	}
	public String gettTime() {
		return tTime;
	}
	public void settTime(String tTime) {
		this.tTime = tTime;
	}
	public String gettTicketPrice() {
		return tTicketPrice;
	}
	public void settTicketPrice(String tTicketPrice) {
		this.tTicketPrice = tTicketPrice;
	}
	public String gettHallID() {
		return tHallID;
	}
	public void settHallID(String tHallID) {
		this.tHallID = tHallID;
	}
}